name       : python-petact
version    : 0.1.2
release    : 2
source     :
    - https://files.pythonhosted.org/packages/5f/89/62b285704ac9823ade8178a1a4c8bcd3529871de3c162084b8dde6d0d6ff/petact-0.1.2.tar.gz : 5dcb0d44f86a601e41a2def9770993cd0ea45c76d37eb3f35e3dd61aa50350e6
license    : MIT
component  : programming.python
summary    : A package extraction tool for Python
description: |
    Petact is a library used for installing and updating compressed tar files. When install_package is called, it downloads an md5 file and compares it with the md5 of the locally downloaded tar. If they are different, the old extracted files are deleted and the new tar is downloaded and extracted to the same place.
rundeps    :
    - python3
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
